# Generated by Django 4.2.5 on 2023-09-08 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVDataset',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chroma_stft_mean', models.FloatField()),
                ('chroma_stft_var', models.FloatField()),
                ('rms_mean', models.FloatField()),
                ('rms_var', models.FloatField()),
                ('spectral_centroids_mean', models.FloatField()),
                ('spectral_centroids_var', models.FloatField()),
                ('spectral_bandwidth_mean', models.FloatField()),
                ('spectral_bandwidth_var', models.FloatField()),
                ('rolloff_mean', models.FloatField()),
                ('rolloff_var', models.FloatField()),
                ('zcr_mean', models.FloatField()),
                ('zcr_var', models.FloatField()),
                ('harmony_mean', models.FloatField()),
                ('harmony_var', models.FloatField()),
                ('tempo_mean', models.FloatField()),
                ('tempo_var', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('music', models.FileField(null=True, upload_to='')),
                ('prediction', models.TextField(null=True)),
                ('exists_in_csv', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.features')),
            ],
        ),
        migrations.CreateModel(
            name='Retraining',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('genre_feedback', models.CharField(choices=[('blues', 'Blues'), ('classical', 'Classical'), ('country', 'Country'), ('disco', 'Disco'), ('hiphop', 'Hip Hop'), ('jazz', 'Jazz'), ('metal', 'Metal'), ('pop', 'Pop'), ('reggae', 'Reggae'), ('rock', 'Rock')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('predict', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.predict')),
            ],
        ),
    ]
