# Generated by Django 4.2.5 on 2023-09-07 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_csvdataset_retraining_predict_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predict',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.features'),
        ),
    ]
